# Generated by Django 6.0.4 on 2026-04-25 09:59

import backgammon.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Game",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("waiting", "Waiting for opponent"),
                            ("active", "Active"),
                            ("finished", "Finished"),
                        ],
                        default="waiting",
                        max_length=16,
                    ),
                ),
                (
                    "victory_type",
                    models.CharField(
                        blank=True,
                        choices=[("oin", "Oin"), ("mars", "Mars")],
                        max_length=8,
                    ),
                ),
                ("board", models.JSONField(default=backgammon.models.initial_board)),
                ("borne_off", models.JSONField(default=dict)),
                ("dice", models.JSONField(default=list)),
                ("remaining_moves", models.JSONField(default=list)),
                ("has_rolled", models.BooleanField(default=False)),
                ("head_moves_this_turn", models.PositiveSmallIntegerField(default=0)),
                ("turn_number", models.PositiveIntegerField(default=1)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "black_player",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="black_backgammon_games",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "current_player",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="current_backgammon_games",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "white_player",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="white_backgammon_games",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "winner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="won_backgammon_games",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="GameMove",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("join", "Join"),
                            ("roll", "Roll"),
                            ("move", "Move"),
                            ("bear_off", "Bear off"),
                            ("finish", "Finish"),
                        ],
                        max_length=16,
                    ),
                ),
                ("dice", models.JSONField(default=list)),
                (
                    "source_point",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                (
                    "target_point",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                ("distance", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("board", models.JSONField(default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "game",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="moves",
                        to="backgammon.game",
                    ),
                ),
                (
                    "player",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="PlayerStats",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("games_played", models.PositiveIntegerField(default=0)),
                ("wins", models.PositiveIntegerField(default=0)),
                ("losses", models.PositiveIntegerField(default=0)),
                ("oin_wins", models.PositiveIntegerField(default=0)),
                ("mars_wins", models.PositiveIntegerField(default=0)),
                ("oin_losses", models.PositiveIntegerField(default=0)),
                ("mars_losses", models.PositiveIntegerField(default=0)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="backgammon_stats",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "player stats",
            },
        ),
    ]
