# Generated by Django 6.0.6 on 2026-06-14 11:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def seed_notification_display_setting(apps, schema_editor):
    AppSetting = apps.get_model("backgammon", "AppSetting")
    AppSetting.objects.get_or_create(
        key="BACKGAMMON_NOTIFICATION_DISPLAY_MS",
        defaults={
            "value": str(settings.BACKGAMMON_NOTIFICATION_DISPLAY_MS),
            "is_enabled": False,
        },
    )


class Migration(migrations.Migration):

    dependencies = [
        ("backgammon", "0004_allow_empty_game_dice"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="GameNotification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.CharField(max_length=160)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "game",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to="backgammon.game",
                    ),
                ),
                (
                    "recipient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="received_backgammon_notifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "sender",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sent_backgammon_notifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["created_at"],
                "indexes": [
                    models.Index(
                        fields=["game", "recipient", "-created_at"],
                        name="backgammon__game_id_7344c2_idx",
                    )
                ],
            },
        ),
        migrations.RunPython(
            seed_notification_display_setting,
            migrations.RunPython.noop,
        ),
    ]
