# Generated by Django 6.0.6 on 2026-06-23

from django.db import migrations, models


def seed_quick_notification_presets(apps, schema_editor):
    QuickNotificationPreset = apps.get_model(
        "backgammon",
        "QuickNotificationPreset",
    )
    presets = (
        ("🎉", "Поздравляю 🎉", 10),
        ("🙂", "Нет связи! Перезвони 🙂", 20),
        ("🎲", "Have a good game!", 30),
        ("📝", "And then they’ll write: it was a duplicate", 40),
        ("🤔", "Interesting move", 50),
    )
    for emoji, text, sort_order in presets:
        QuickNotificationPreset.objects.get_or_create(
            text=text,
            defaults={
                "emoji": emoji,
                "sort_order": sort_order,
            },
        )


class Migration(migrations.Migration):

    dependencies = [
        ("backgammon", "0005_gamenotification"),
    ]

    operations = [
        migrations.CreateModel(
            name="QuickNotificationPreset",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("emoji", models.CharField(max_length=16)),
                ("text", models.CharField(max_length=160, unique=True)),
                (
                    "sort_order",
                    models.PositiveIntegerField(default=0, db_index=True),
                ),
            ],
            options={
                "ordering": ["sort_order", "id"],
            },
        ),
        migrations.RunPython(
            seed_quick_notification_presets,
            migrations.RunPython.noop,
        ),
    ]
