# Generated by Django 6.0.6 on 2026-08-15 09:52

import django.core.validators
from django.db import migrations, models


def backfill_party_numbers(apps, schema_editor):
    Game = apps.get_model("backgammon", "Game")
    next_numbers = {}

    games = (
        Game.objects.exclude(white_player_id__isnull=True)
        .exclude(black_player_id__isnull=True)
        .order_by("created_at", "pk")
    )
    for game in games.iterator():
        pair = tuple(sorted((game.white_player_id, game.black_player_id)))
        party_number = next_numbers.get(pair, 0) + 1
        Game.objects.filter(pk=game.pk).update(party_number=party_number)
        next_numbers[pair] = party_number


class Migration(migrations.Migration):

    dependencies = [
        ("backgammon", "0007_game_setup_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="game",
            name="party_number",
            field=models.PositiveIntegerField(
                blank=True,
                null=True,
                validators=[django.core.validators.MinValueValidator(1)],
            ),
        ),
        migrations.RunPython(backfill_party_numbers, migrations.RunPython.noop),
    ]
