# Generated by Django 6.0.6 on 2026-08-16 09:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backgammon", "0009_planned_opponent"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="backgammonplayerpreference",
            name="default_opponent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="preferred_by_backgammon_players",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
