services:
  app:
    image: ${DOCKER_IMAGE}
    container_name: games-app
    env_file:
      - .env
    environment:
      APP_SERVICE: app
      CI_DOCKER_IMAGE_TAG: ${CI_DOCKER_IMAGE_TAG:-}
      SQLITE_PATH: /app/.data/db.sqlite3
      REDIS_URL: redis://redis:6379/0
    ports:
      - 127.0.0.1:${APP_PORT}:${APP_PORT}
    volumes:
      - ${PWD}/.data:/app/.data
    depends_on:
      - redis

  redis:
    image: redis:7-alpine
    container_name: games-redis
