name: Test
on:
  pull_request:
    branches:
      - "main"
  push:
    branches:
      - "main"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Prepare .env file
        run: |
          cp .env.template .env
          echo "DJANGO_SECRET_KEY=test-secret-key" >> .env
          echo "DJANGO_ALLOWED_HOSTS=localhost,127.0.0.1,testserver" >> .env
          mkdir -p .data
          sudo chown 1007:1007 .data
          chmod 770 .data
          env >> .env

      - name: Build images
        run: docker compose build test

      - name: Run linters
        run: docker compose up --exit-code-from lint lint

      - name: Run tests
        run: docker compose up --exit-code-from test test
